name: flutter_webapi_first_course
description: Projeto do primeiro curso de WebAPI da Formação Flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 
  uuid: ^4.1.0
  google_fonts: ^6.1.0
  http: ">=0.13.4 <2.0.0"
  http_interceptor: ">=1.0.2 <3.0.0"
  logger: ^2.0.2+1
  flutter_secure_storage:

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
